##' Create a rlite connection.  This function is designed to be used
##' in other packages and not generally directly by end-users.
##' However it is possible and safe to use.  See the \code{RedisAPI}
##' package for a complete example interface.
##'
##'
##' This function creates a list of functions, appropriately bound to
##' a pointer to a Redis connection.  This is designed for package
##' authors to use so without having to ever deal with the actual
##' pointer itself (which cannot be directly manipulated from R
##' anyway).
##'
##' The returned list has elements, all of which are functions:
##'
##' \describe{
##' \item{\code{config()}}{The configuration information,
##'   as generated by \code{\link{rlite_config}}}.
##'
##' \item{\code{reconnect()}}{Attempt reconnection of a connection
##' that has been closed, through serialisation/deserialiation or
##' through loss of internet connection.}
##'
##' \item{command(cmd)}{Run a Redis command.  The format of this
##' command will be documented elsewhere.}
##'
##' \item{pipeline(cmds)}{Run a pipeline of Redis commands.}
##' }
##'
##' Note that unlike \code{redux}, \code{rrlite} does not support
##' subscriptions because that would require asynchronous
##' communication (especially with \code{:memory:} databases).
##'
##' @title Create a rlite connection
##' @param config Configuration parmeters as generated by
##'   \code{\link[RedisAPI]{redis_config}}.
##' @useDynLib rrlite, .registration = TRUE
##' @export
rlite_connection <- function(config=rlite_config()) {
  config <- rlite_config(config)
  ptr <- rlite_connect(config)
  ret <-
    list(
      config=function() {
        config
      },
      reconnect=function(cmd) {
        ptr <<- rlite_connect(config)
        invisible()
      },
      command=function(cmd) {
        rlite_command(ptr, cmd)
      },
      pipeline=function(cmds) {
        rlite_pipeline(ptr, cmds)
      })
  ## NOTE: no subscribe support.
  attr(ret, "type") <- "rlite"
  class(ret) <- "redis_connection"
  ret
}

##' rlite configuration settings.  Based on the \code{redis_config}
##' function but with additional tweaks for rlite.  The differences
##' between this configuration and \code{\link{redis_config}} is that:
##'
##' \itemize{
##'
##' \item{\code{RLITE_URL} takes precendence over \code{REDIS_URL} if
##' both are present (otherwise \code{REDIS_URL} will still be used).}
##'
##' \item{A host of \code{localhost} or \code{127.0.0.1}, which is
##' \code{redis_config}'s default, will map to a filename of
##' \code{:memory:} for a transient in-memory store.}
##' }
##'
##' The \code{port} entry will be ignored, but the \code{password} and
##' \code{db} entries will be used if present.  \code{path} is
##' equivalent to \code{host}.
##'
##' @title rlite configuration
##' @param ... Arguments passed to \code{\link{redis_config}}; see
##'   that file for more information.
##' @export
rlite_config <- function(...) {
  if (Sys.getenv("RLITE_URL") != "") {
    ## Dear god what a mess:
    old <- Sys.getenv("REDIS_URL", NA_character_)
    if (is.na(old)) {
      on.exit(Sys.unsetenv("REDIS_URL"))
    } else {
      on.exit(Sys.setenv(REDIS_URL=old))
    }
    Sys.setenv(REDIS_URL=Sys.getenv("RLITE_URL"))
  }
  config <- RedisAPI::redis_config(...)
  if (config$host %in% c("localhost", "127.0.0.1")) {
    config$host <- ":memory:"
  }
  class(config) <- c("rlite_config", class(config))
  config
}
