# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_rlite_noop <- function(ip, port) {
    invisible(.Call('rrlite_test_rlite_noop', PACKAGE = 'rrlite', ip, port))
}

test_rlite_add <- function(ip) {
    invisible(.Call('rrlite_test_rlite_add', PACKAGE = 'rrlite', ip))
}

test_rlite_db <- function(filename) {
    .Call('rrlite_test_rlite_db', PACKAGE = 'rrlite', filename)
}

test_rlite_write <- function(filename, command) {
    invisible(.Call('rrlite_test_rlite_write', PACKAGE = 'rrlite', filename, command))
}

test_rlite_read <- function(filename) {
    .Call('rrlite_test_rlite_read', PACKAGE = 'rrlite', filename)
}

